### ISSUE TITLE
do you have English version pls 

### ISSUE THREAD

**Issue by Sandy4321** [alex-sokolov2011/100_Numpy_exercises_Rus_ver#6]
do you have English version pls

**Comment by alex-sokolov2011** [comment]
Hi Sandy!
Thank you for your attention for my repo. I will be glad if it is useful.
I don't have an English version yet.
you can see the original, https://github.com/rougier/numpy-100
but it's poorer and really old.
I plan to make an English version next year

I will be grateful for the star repo
https://github.com/alex-sokolov2011/100_Numpy_exercises_Rus_ver

**Comment by Sandy4321** [comment]
Sure
Star added
